# Generated by Django 4.0.1 on 2022-06-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailId', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=400)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('phone_no', models.IntegerField()),
                ('profile', models.ImageField(blank=True, upload_to='profile_pics/')),
                ('signature', models.ImageField(blank=True, upload_to='signature_pics/')),
                ('caste_certificate', models.ImageField(upload_to='category/caste_certificate/')),
                ('qualification', models.ImageField(upload_to='qualification/')),
            ],
        ),
    ]
