# Generated by Django 4.0.1 on 2022-06-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_login_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='permanent_address',
            field=models.CharField(default=0, max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='login',
            name='caste_certificate',
            field=models.FileField(upload_to='category/caste_certificate/'),
        ),
        migrations.AlterField(
            model_name='login',
            name='profile',
            field=models.FileField(upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='login',
            name='qualification',
            field=models.FileField(upload_to='qualification/'),
        ),
        migrations.AlterField(
            model_name='login',
            name='signature',
            field=models.FileField(upload_to='signature_pics/'),
        ),
    ]
