# Generated by Django 4.0.1 on 2022-07-05 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_login_permanent_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='registration_no',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
